version: '2.4'
   
services:
     
  apts:
    container_name: apts
    image: apts
    # The following options are useful when running 'protocoltest' below:
    #    -v: prints the name of each test as it is run; otherwise, printed more concisely
    #    -x: stop after the first test failure; otherwise, runs all tests
    #    --capture=tee-sys: print stdout/stderr to screen for all tests; otherwise, only prints for failed tests
    command: protocoltest -vx
    build:
      context: apts
    volumes:
      - type: bind
        source: ./apts/src/aut.py
        target: /aries-protocol-test-suite/aut.py
    networks:
      local:

  ledger:
    container_name: ledger
    image: ledger
    build:
      context: ledger
    command: /bin/bash -c '/home/indy/bin/start-ledger'
    working_dir: /home/indy
    volumes:
       - ledger:/var/lib/indy
    # Set the EXTERNAL_IP environment variable to access the ledger externally
    # environment:
    #  - EXTERNAL_IP=<YOUR_IP_ADDR>
    ports:
      - "8000:8000"
      - "9711:9711"
      - "9712:9712"
      - "9713:9713"
      - "9714:9714"
      - "9715:9715"
      - "9716:9716"
      - "9717:9717"
      - "9718:9718"
    networks:
      local:
        ipv4_address: 10.5.0.5

volumes:
  ledger:

networks:
  local:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
